;;; themes/doom-zed-simple-theme.el -*- lexical-binding: t; -*-

(require 'doom-themes)

(defgroup doom-zed-simple-theme nil
  "Options for doom-zed-simple-theme."
  :group 'doom-themes)

(def-doom-theme doom-zed-simple
  "A dark theme based on the Zed Simple dark theme with local overrides."

  ((bg         '("#040300" nil       nil))
   (bg-alt     '("#0b0b0a" nil       nil))
   (base0      '("#040300" "black"   "black"))
   (base1      '("#0a0a09" "#1e1e1e" "brightblack"))
   (base2      '("#121211" "#2e2e2e" "brightblack"))
   (base3      '("#252524" "#262626" "brightblack"))
   (base4      '("#303030" "#3f3f3f" "brightblack"))
   (base5      '("#353532" "#525252" "brightblack"))
   (base6      '("#444b6a" "#6b6b6b" "brightblack"))
   (base7      '("#7a7a7a" "#979797" "brightblack"))
   (base8      '("#a9b1d6" "#dfdfdf" "white"))
   (fg         '("#a9b1d6" "#bfbfbf" "brightwhite"))
   (fg-alt     '("#8a8a80" "#2d2d2d" "white"))

   (grey       '("#7a7a7a" "grey"    "grey"))
   (red        '("#ff5050" "#ff6655" "red"))
   (orange     '("#dfef20" "#dd8844" "brightred"))
   (green      '("#9acf6a" "#99bb66" "green"))
   (teal       '("#0db9d7" "#44b9b1" "brightgreen"))
   (yellow     '("#dfef20" "#ecbe7b" "yellow"))
   (blue       '("#a9b1d5" "#51afef" "brightblue"))
   (dark-blue  '("#343a52" "#2257A0" "blue"))
   (magenta    '("#ef2fff" "#c678dd" "brightmagenta"))
   (violet     '("#bb9af7" "#a9a1e1" "magenta"))
   (cyan       '("#2ac3de" "#46D9FF" "brightcyan"))
   (dark-cyan  '("#b4f9f8" "#5699AF" "cyan"))

   (highlight      blue)
   (vertical-bar   base4)
   (selection      base3)
   (builtin        fg)
   (comments       base6)
   (doc-comments   base6)
   (constants      blue)
   (functions      "#cccccc")
   (keywords       yellow)
   (methods        "#cccccc")
   (operators      fg)
   (type           grey)
   (strings        green)
   (variables      "#ffffff")
   (numbers        fg)
   (region         base3)
   (error          red)
   (warning        yellow)
   (success        green)
   (vc-modified    cyan)
   (vc-added       green)
   (vc-deleted     red))

  (
   (lazy-highlight :background base4 :foreground fg)
   (line-number :foreground "#505050" :background bg)
   (line-number-current-line :foreground magenta :background bg)
   (hl-line :background bg-alt)
   (solaire-default-face :background bg)
   (solaire-hl-line-face :background bg-alt)
   (vterm-color-default :background bg :foreground fg)
   (mode-line :background base1 :foreground fg :box nil)
   (mode-line-inactive :background bg :foreground fg-alt :box nil)
   (corfu-default :background bg-alt)
   (corfu-current :background base3)
   (company-tooltip :background bg-alt)
   (company-tooltip-selection :background base3)
   (tooltip :background bg-alt)
   (markdown-code-face :background base1)
   (markdown-inline-code-face :background base1)
   (markdown-pre-face :background base1)
   (eldoc-box-body :background bg)
   (eldoc-box-border :background base4)
   (font-lock-function-name-face :foreground functions :weight 'medium)
   (font-lock-type-face :foreground type :weight 'medium)
   (font-lock-variable-name-face :foreground variables)
   (font-lock-property-name-face :foreground fg)
   (font-lock-property-use-face :foreground fg)
   ))

;;; doom-zed-simple-theme.el ends here
