# Background / Foreground
background              #062329
foreground              #d1b897
selection_background    #11494c
selection_foreground    #ffffff

# Cursor
cursor                  #d1b897
cursor_text_color       background

# URL color
url_color               #4ac1c9

# Window border
active_border_color     #11494c
inactive_border_color   #04171c
bell_border_color       #ffaa00

# Tab bar
tab_bar_background      #04171c
active_tab_background   #11494c
active_tab_foreground   #ffffff
inactive_tab_background #04171c
inactive_tab_foreground #a89379

# -----------------------------------------------------------------------------
# ANSI colors
# -----------------------------------------------------------------------------

# black
color0                  #04171c
color8                  #186569

# red
color1                  #ff0000
color9                  #ff6655

# green
color2                  #44b340
color10                 #99bb66

# yellow
color3                  #e6db74
color11                 #ecbe7b

# blue
color4                  #42a5f5
color12                 #51afef

# magenta
color5                  #fd5ff0
color13                 #c678dd

# cyan
color6                  #2ec09c
color14                 #7ad0c6

# white
color7                  #d1b897
color15                 #ffffff

# Marks
mark1_background        #44b340
mark1_foreground        #062329

mark2_background        #e6db74
mark2_foreground        #062329

mark3_background        #ff0000
mark3_foreground        #062329
