blur:

	{
		method = "gaussian";
		size = 4;
		deviation = 2.5;
	}

rules: (

	{
		blur-background = false;
		fade = false;
	},

	{
		match = "window_type = 'normal'
                && !(class_g = 'Rofi'
                    || class_g = 'Viewnior'
                    || class_g = 'mpv')";

		fade = true;	#-fade-switch
		shadow = true;	#-shadow-switch
	},

	{
		match = "window_type = 'dialog'";
		fade = true;	#-fade-switch
		shadow = true;	#-shadow-switch
	},

	{
		match = "window_type = 'tooltip'";
		corner-radius = 0;
		opacity = 0.90;
	},

    {
		match = "fullscreen";
		corner-radius = 0;
	},

	{
		match = "window_type = 'dropdown_menu' || window_type = 'menu' || window_type = 'popup' || window_type = 'popup_menu'";
		corner-radius = 0;
        shadow = false;
	},

## ----- Single apps rules ----- ##

    {
        match = "class_g = 'Dunst'";
        shadow = false;
        corner-radius = 0;
    },

    {
        match = "class_g = 'bspwm-scratch' || class_i = 'bspwm-scratch'";
        corner-radius = 0;
        shadow = false;
		blur-background = false;	#-blur-switch
    },

    {
        match = "name = 'Eww - bar'     || "
                "class_g = 'Polybar'    || "
                "window_type = 'dock'   || "
                "class_g = 'Eww'";
        fade = true;
        corner-radius = 0;
        shadow = false;
    },

    {
        match = "class_g = 'jgmenu'";
        shadow = false;
        corner-radius = 0;
    },

	{
        match = "name = 'Eww - launchermenu'";
    },

    {
        match = "name = 'Eww - music'";
    },

    {
        match = "name = 'Eww - csheet'";
    },

	{
		match = "class_g = 'firefox'		|| "
				"class_g = 'Screenkey'		|| "
				"_GTK_FRAME_EXTENTS@";
		shadow = false;
	},

    {
		match = "class_g = 'Rofi'           || "
				"class_g = 'Viewnior'       || "
				"class_g = 'mpv'            || "
				"class_g = 'retroarch'";
		corner-radius = 0;
		fade = true;	#-fade-switch
        shadow = false;
	}
)
