# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks


# Global properties
separator=true
separator_block_width=10

# [documentation]
# full_text=Documentation
# website=https://vivien.github.io/i3blocks
# command=xdg-open "$website"
# color=#f12711

[greetings]
color=#fbef19
command=echo "$USER"
interval=once

[network]
command=/home/$USER/.config/i3blocks/scripts/net.sh
color=#00ff10
interval=10

[volume]
command=/home/$USER/.config/i3blocks/scripts/volume.sh
LABEL=♪
#LABEL=VOL 
interval=1
signal=10
#STEP=5%
MIXER=default
#SCONTROL=[determined automatically]
#NATURAL_MAPPING=0

[brightness]
command=/home/$USER/.config/i3blocks/scripts/brightness.sh
color=#5060ff
interval=once
signal=11

[battery]
command=/home/$USER/.config/i3blocks/scripts/battery.sh
interval=10

[memory]
command=/home/$USER/.config/i3blocks/scripts/mem.sh
label=󰍛 
interval=30

[disk]
command=/home/$USER/.config/i3blocks/scripts/disk.sh
LABEL= 
#DIR=$HOME
#ALERT_LOW=10
interval=30

[time]
command=date '+%Y-%m-%d %H:%M:%S'
interval=1
color=#00ff10
